### ISSUE TITLE
USER STORY: Home Page First Impression (above fold)

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#1]
As a **user** I can **see a visually appealing homepage with store name, logo, tagline, high-quality image and call to action button** so that **I get a good first impression of the store**.

### **Acceptance Criteria**

   - Given a user accesses the homepage
   - When the homepage loads
   - Then the user immediately sees the store name, logo, tagline, high-quality image relevant to the store business and call-to-action button prominently displayed.

### **Tasks**

- [x] Design the homepage layout using Bootstrap for responsive layout.
- [x] Add the store name, logo, and tagline.
- [x] Upload high-quality appealing image relevant to the store business.
- [x] Create and place a call-to-action button.
- [x]   Test the homepage for visual appeal and functionality.
- [x] Check the responsiveness and visual appeal across different devices to ensure a uniform experience, and adjust layouts and font sizes as needed.

**Comment by KatePaulauskas** [comment]
The above fold section is created including the store name, logo, tagline, high-quality engaging image and call-to-action button to represent the nature of the store immediately.
