### ISSUE TITLE
USER STORY: Account Creation

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#10]
As a **new customer** I can **create a new account through Log In bar** so that **I can view my profile and past purchases**.

### **Acceptance Criteria**

- Given an email a customer can register an account
- When the user enters their details and submits the form
- Then the account is created and the user is redirected to the home page
- When the user logs in, they can view their profile details and order history

### **Tasks**

- [x] Implement the user registration form using Django's authentication framework all-auth and Crispy Forms
- [x] Set up validation for email uniqueness and password confirmation
- [x] Set up error handling
- [x] Create views and URLs for the registration form and redirection upon successful registration.
- [x] Test account creation functionality
- [x] Check the responsiveness and visual appeal across different devices
- [x]  Implement a user profile page that displays the customer's personal details.
- [x] Create a view and URL for the user profile page.
- [x] Implement functionality to display the user's past orders on their profile page.
- [x] Test the display and functionality of the profile and order history pages to ensure accuracy.
- [x] Ensure that the profile and order history pages are responsive and visually appealing across different devices.

**Comment by KatePaulauskas** [comment]
New customers are now able to register their accounts.

**Comment by KatePaulauskas** [comment]
After logging in, a customer can view their profile page with the option to save or update delivery details and view past purchases.
