### ISSUE TITLE
USER STORY: Account Creation Email Confirmation

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#11]
As a **new customer** I can **receive an email confirmation after registering an account** so that **I know my account setup was successful**.

### **Acceptance Criteria**

- Given a user registers a new account
- When the registration is successful
- Then an email confirmation is sent to the user

### **Tasks**

- [x] Implement email functionality in Django
- [x] Design the email template
- [x] Test email sending after registration

**Comment by KatePaulauskas** [comment]
Users now receive an email confirmation after registering an account.
