### ISSUE TITLE
USER STORY: Login Access

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#12]
As a **existing customer** I can **log in to my account** so that **I can access my account and purchase history**.

### **Acceptance Criteria**

- Given a user is on the login page
- When the user enters their credentials and submits the form
- Then the user is logged in and redirected to their account page

### **Tasks**

- [x]  Implement the user login form using Django's authentication framework all-auth and Crispy Forms
- [x] Create views and URLs for the login form and redirection upon successful login
- [x] Test login functionality
- [x] Check the responsiveness and visual appeal across different devices

**Comment by KatePaulauskas** [comment]
Existing users are now able to log in to their accounts.
