### ISSUE TITLE
USER STORY: Password Reset

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#13]
As an **existing customer** I can **reset my password if I forget it** so that **I can regain access to my account**.

### **Acceptance Criteria**

- Given a user clicks on the password reset link on the login form
- When the user enters their email and submits the form
- Then a password reset link is sent to their email

### **Tasks**

- [x] Design and implement the password reset form using Django's authentication framework all-auth
- [x] Implement password reset logic for Gmail
- [x] Test password reset functionality
- [x] Check the responsiveness and visual appeal across different devices

**Comment by KatePaulauskas** [comment]
Users are now able to reset passwords.
