### ISSUE TITLE
USER STORY: Update Personal Details

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#14]
As an **existing customer** I can **update my default delivery details** so that **my account information stays accurate and up to date**.

### **Acceptance Criteria**

- Given a user is logged in and on their account page
- When the user updates their details and submits the form
- Then the user's account information is updated
- When the user clicks on 'save this delivery information to my profile'
- Then the user's account information is updated

### **Tasks**

- [x] Design and implement the user account page
- [x] Implement account update logic in Django views
- [x] Test updating personal details functionality
- [x] Check the responsiveness and visual appeal across different devices

**Comment by KatePaulauskas** [comment]
Shoppers are now able to update their delivery details.
