### ISSUE TITLE
USER STORY: Category Browsing

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#16]
As a **user** I can **browse watches by categories such as brand or gender,** so that **I can find what I’m looking for easily**.

### **Acceptance Criteria**

- Given a user is on the shop page
- When the user selects a category filter
- Then only products within that category are displayed

### **Tasks**

- [x] Implement category browsing functionality
- [x] Integrate category filter logic into Django views
- [x] Test category browsing functionality
- [x] Check the responsiveness and visual appeal across different devices

**Comment by KatePaulauskas** [comment]
Site users are now able to browse the shop by such categories, as brand or gender.
