### ISSUE TITLE
USER STORY: Keyword Search

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#17]
As a **user** I can **use search bar to find specific watches by keyword or model number** so that **I can quickly locate desired products**.

### **Acceptance Criteria**

- Given a user is on any page
- When the user enters a keyword in the search bar and submits
- Then the search results matching the keyword are displayed

### **Tasks**

- [x] Implement search logic in Django views to filter products based on keywords
- [x] Test keyword search functionality
- [x] Check the responsiveness and visual appeal across different devices

**Comment by KatePaulauskas** [comment]
Site users are now able to use the search bar to find a specific watch by keyword.
