### ISSUE TITLE
USER STORY: Multiple Filter Application

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#18]
As a **user** I can **apply multiple filters (e.g., brand and gender) on the shop page** so that **I can narrow down the selection**.

### **Acceptance Criteria**

  - Given a user is on the product browsing page
  - When the user applies multiple filters
  - Then the filtered results are displayed

### **Tasks**

- [x] Design and implement filter options using HTML, CSS, and Bootstrap for responsive layout
- [x] Implement filter logic in Django views
- [x] Test filter application functionality
- [x] Check the responsiveness and visual appeal across different devices

**Comment by KatePaulauskas** [comment]
Site users can now apply multiple filters on the shop page to narrow the search.
