### ISSUE TITLE
USER STORY: Sort All Products Page Results

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#19]
As a **user** I can **sort search results by criteria like rating, price, and name** so that **I can view products in my preferred order**.

### **Acceptance Criteria**

- Given a user is on the product browsing page
- When the user selects a sort option
- Then the sorted results are displayed

### **Tasks**

- [x] Design and implement sort options using HTML, CSS, and Bootstrap for responsive layout
- [x] Implement sorting logic in Django views
- [x] Test sorting functionality
- [x] Check the responsiveness and visual appeal across different devices

**Comment by KatePaulauskas** [comment]
Users are now able to apply sorting functionality to the store products.
