### ISSUE TITLE
USER STORY: Navigation Menu

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#2]
As a **user**, I can **access the navigation menu from any page** so that **I can easily access site pages and find what I’m looking for or discover what is available.**

### **Acceptance Criteria**

- Given a user accesses the site
- When the homepage loads
- Then the navigation menu is easily accessible in the header of the site
- When a user clicks on any item in the site menu
- Then the user is directed to the appropriate section or page of the site

### **Tasks**

- [x] Design and implement the navigation menu using Bootstrap for responsive layout
- [x] Ensure all navigation links are working correctly.
- [x] Conduct user testing to ensure ease of navigation.
- [x] Check the responsiveness and visual appeal across different devices to ensure a uniform experience, adjust layouts and font sizes as needed.

**Comment by KatePaulauskas** [comment]
Site users can easily access site pages via the header menu.
