### ISSUE TITLE
USER STORY: Product Sorting

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#20]
As a **user** I can **sort store products** so that **I can find the best-priced, and most popular product or sort the products by name**.

### **Acceptance Criteria**

- Given a user is on the shop page
- When the user selects a sort option
- Then the sorted results are displayed

### **Tasks**

- [x] Design and implement sort options using HTML, CSS, and Bootstrap for responsive layout
- [x] Implement sorting logic in Django views
- [x] Test sorting functionality
- [x] Check the responsiveness and visual appeal across different devices

**Comment by KatePaulauskas** [comment]
Site visitors are now able to apply sorting functionality to the store products.

**Comment by KatePaulauskas** [comment]
Users are now able to sort store products
