### ISSUE TITLE
USER STORY: Search Query and Result Count Display

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#21]
As a **user** I can **clearly see my search query and the total number of results** so that **I can assess if the desired product is offered by the store**.

### **Acceptance Criteria**

- Given a user performs a search
- When the search results are displayed
- Then the search query and number of results are clearly shown

### **Tasks**

- [x] Display the search query and result count using HTML, CSS, and Bootstrap for responsive layout
- [x] Ensure search clarity in Django views
- [x] Test the display of search query and result count
- [x] Check the responsiveness and visual appeal across different devices

**Comment by KatePaulauskas** [comment]
Site users are now able to see their search query and the total number of search results.
