### ISSUE TITLE
USER STORY: Product Page

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#22]
As a **shopper** I can **see detailed product descriptions, specifications, and image** so that **I can understand the product features**.

### **Acceptance Criteria**

- Given a shopper is on the product detail page
- When the page loads
- Then the shopper can see detailed descriptions, specifications, and image

### **Tasks**

- [x] Add products through the Django admin panel to populate the product database.
- [x] Design and implement the product detail page using HTML, CSS, and Bootstrap for responsive layout
- [x]  Implement a Django view to retrieve and display the product details on the product detail page.
- [x] Test the display of product details, ensuring all data is correctly pulled from the database.
- [x] Check the responsiveness and visual appeal of the product detail page across different devices.

**Comment by KatePaulauskas** [comment]
Dynamic product page is set and site visitors can now see the details of each product on a separate page upon clicking on the product on the Shop page.
