### ISSUE TITLE
USER STORY: Products' Reviews

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#23]
As a **shopper** I can **view customer reviews and ratings** so that **I can gauge the quality and satisfaction of other buyers**.

### **Acceptance Criteria**

- Given a shopper is on the product detail page
- When the page loads
- Then the shopper can see customer reviews and ratings

### **Tasks**

- [ ] Design and implement the customer review section using HTML, CSS, and Bootstrap for responsive layout
- [ ] Integrate customer reviews and ratings in Django models
- [ ] Populate the review section with sample reviews and ratings
- [ ] Test the display and functionality of customer reviews
- [ ] Check the responsiveness and visual appeal across different devices
