### ISSUE TITLE
USER STORY: Update Cart 

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#27]
As a **shopper**, I can **remove or update quantities of items in my cart** so that I can **adjust my order**.

**Acceptance Criteria:**
- Given a shopper is on the shopping cart page
- When the shopper updates quantities or removes items
- Then the cart reflects the changes

**Tasks:**
- [x] Implement functionality to update quantities and remove items in the cart using HTML, CSS, and Bootstrap for a responsive layout
- [x] Update Django views to handle cart updates
- [x] Ensure the cart dynamically updates the total cost when changes are made
- [x] Provide user feedback for any errors when viewing or updating the cart
- [x] Test the update and removal functionality
- [x] Check the responsiveness and visual appeal across different devices

**Comment by KatePaulauskas** [comment]
Users can now update the quantity of the items in the cart or remove items from the cart.
