### ISSUE TITLE
USER STORY: Select Product Quantity

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#28]
As a **shopper**, I can **select product quantity** so that I can **customize my choice before adding it to the cart**.

### **Acceptance Criteria**

- Given a shopper is on a product detail page
- When the page loads
- Then the shopper can see options to select product quantity
- When the shopper selects product quantity
- Then the selections are captured correctly and can be added to the cart

### **Tasks**

- [x] Design and implement product quantity selector
- [x] Ensure the quantity selector is intuitive and user-friendly
- [x] Integrate the selection functionality in Django models and views to capture and process the selected attributes and quantity
- [x] Test the selection functionality to ensure the options and quantity are accurately captured and processed
- [x] Validate the visual appeal and responsiveness of the product option selectors across different devices
- [x] Provide feedback to the user in case of invalid selections or errors (e.g., out-of-stock options)

**Comment by KatePaulauskas** [comment]
Users are now able to select the quantity of products they want to add to their cart.
