### ISSUE TITLE
USER STORY: Add Customer Details at Checkout

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#29]
As a **shopper**, I can **enter my customer details during checkout** so that I can **complete my purchase**.

### **Acceptance Criteria:**
- Given a shopper is on the checkout page
- When the shopper enters their customer details
- Then the customer details are saved and used for the order

### **Tasks:**
- [x] Design and implement the customer details form using HTML, CSS, and Bootstrap for a responsive layout
- [x] Implement logic in Django views to save the customer details
- [x] Test the customer details entry functionality
- [x] Check the responsiveness and visual appeal across different devices

**Comment by KatePaulauskas** [comment]
Users are now able to add their details at the checkout.
