### ISSUE TITLE
USER STORY: Search Bar

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#3]
As a **user**, I can **access the search functionality in the header of the site** so that **I can easily find what I’m looking for or discover what is available**.

### **Acceptance Criteria**

-   Given a user accesses the site
- When the homepage loads
- Then the search bar is prominently placed in the header of the site and functional
- Given a user uses the search bar
- When a search is performed
- Then the user receives relevant search results

### **Tasks**

- [x] Add and design a search bar in the header of the site.
- [x] Ensure the search functionality works correctly.
- [x] Conduct user testing to ensure the search bar is easy to find and use.
- [x] Check the responsiveness and visual appeal across different devices to ensure a uniform experience, adjust layouts and font sizes as needed.

**Comment by KatePaulauskas** [comment]
The search functionality has been successfully added to the header.
