### ISSUE TITLE
USER STORY: Offer Login at Checkout

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#30]
As a **shopper**, I can **be prompted to log in at checkout** so that I can **prefill my details if I have an account**.

### **Acceptance Criteria:**
- Given a shopper is on the checkout page and not logged in
- When the page loads
- Then the shopper is offered the option to log in
- When the shopper logs in
- Then their customer details are prefilled in the relevant fields

### **Tasks:**
- [x] Design and implement the login prompt on the checkout page using HTML, CSS, and Bootstrap for a responsive layout
- [x] Implement logic in Django views to handle shopper login and retrieval of customer details
- [x] Test the login prompt and prefill functionality
- [x] Check the responsiveness and visual appeal across different devices

**Comment by KatePaulauskas** [comment]
Users are now prompted to log in at the checkout if they have an account.
