### ISSUE TITLE
USER STORY: Enter Shipping Address at Checkout

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#32]
As a **shopper**, I can **enter my shipping address** so that **my order can be delivered to me**.

### **Acceptance Criteria:**
- Given a shopper is on the checkout page
- When the shopper enters their shipping address
- Then the shipping address is saved and used for the order

### **Tasks:**
- [x] Design and implement the shipping address form using HTML, CSS, and Bootstrap for a responsive layout
- [x] Implement logic in Django views to save the shipping address
- [x] Test the shipping address entry functionality
- [x] Check the responsiveness and visual appeal across different devices

**Comment by KatePaulauskas** [comment]
Users are now able to add their shipping address at the checkout.
