### ISSUE TITLE
USER STORY: Choose Shipping Method at Checkout

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#33]
As a **shopper** I can **choose a delivery method** so that I can **select how my order will be delivered to me**.

### **Acceptance Criteria:**
- Given a shopper is on the checkout page
- When the shopper selects a shipping method
- Then the selected shipping method is saved and used for the order

### **Tasks:**
- [x] Design and implement the shipping method selection using HTML, CSS, and Bootstrap for a responsive layout
- [x] Implement logic in Django views to save the selected shipping method
- [x] Use JavaScript to display Delivery method selection dynamically
- [x] Test the shipping method selection functionality
- [x] Check the responsiveness and visual appeal across different devices

**Comment by KatePaulauskas** [comment]
Shoppers are now able to choose delivery method at checkout.
