### ISSUE TITLE
USER STORY: Payment Security

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#35]
As a **shopper**, I can **feel my personal and payment information is safe and secure** so that I can **provide the required information in confidence to complete my purchase**.

### **Acceptance Criteria:**
- Given a shopper is on the checkout page
- When the shopper enters their payment information
- Then the information is encrypted and processed securely

### **Tasks:**
- [x] Ensure Stripe uses secure protocols
- [x] Test the security measures for payment information
- [x] Check the responsiveness and visual appeal across different devices
