### ISSUE TITLE
USER STORY: Add a Product as Admin

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#38]
As **an admin** I can **add a product** so that **I can include new items in the store inventory**.

### **Acceptance Criteria**

- Given an admin is logged into the site
- When the admin navigates to the add product page and enters product details
- Then the new product is added to the store inventory

### **Tasks**

- [x] Design and implement the add product form using HTML, CSS, Bootstrap and Crispy Forms
- [x] Implement logic in Django views to handle adding products
- [x] Test the add product functionality
- [x] Check the responsiveness and visual appeal across different devices

**Comment by KatePaulauskas** [comment]
The admin can now add products to the store on the front end.
