### ISSUE TITLE
USER STORY: Edit/Update a Product as Admin

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#39]
As an **admin** I can **edit or update a product** so that **I can change product prices, descriptions, images, and other product criteria**.

### **Acceptance Criteria:**
- Given an admin is logged into the site
- When the admin navigates to the edit product page and updates product details
- Then the product details are updated in the store inventory

**Tasks:**
- [x] Design and implement the edit product form
- [x] Implement logic in Django views to handle editing products
- [x] Test the edit product functionality
- [x] Check the responsiveness and visual appeal across different devices

**Comment by KatePaulauskas** [comment]
The admin can now edit and update products to the store on the front end.
