### ISSUE TITLE
USER STORY: Featured Products

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#4]
As a **user**, I can view **featured products on the home page** so that **I can quickly see what products are popular.**

### **Acceptance Criteria**

- Given a user accesses the homepage
- When the homepage loads
- Then featured products are displayed prominently on the home page
- Given a user clicks on a featured product
- When the product name or image is clicked
- Then the user is taken to the product detail page

### **Tasks**

- [x] Design and display featured products on the homepage in a gallery.
- [x] Link featured products to their detail pages.
- [x] Test the functionality of featured product links.
- [x] Check the responsiveness and visual appeal across different devices to ensure a uniform experience, adjust layouts and font sizes as needed.

**Comment by KatePaulauskas** [comment]
Site visitors are now able to view featured products on the home page.
