### ISSUE TITLE
USER STORY: View Order History

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#41]
As a **shopper** I can **view my order history** so that **I can reference previous purchases**.

### **Acceptance Criteria:**
- Given a shopper is logged into their account
- When the shopper navigates to the profile page
- Then a list of all previous orders is displayed

### **Tasks:**
- [x] Design and implement the order history section using HTML, CSS, and Bootstrap for responsive layout
- [x] Implement logic in Django views to fetch and display order history
- [x] Test the order history functionality
- [x] Check the responsiveness and visual appeal across different devices

**Comment by KatePaulauskas** [comment]
Shoppers are now able to view their orders history.
