### ISSUE TITLE
USER STORY: Brand Connection

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#6]
As a **user** I can **read about the store, its goal, and mission on the home page** so that **I can connect with the values and vision of the business**.

### **Acceptance Criteria**

- Given a user accesses the homepage
-  When the homepage loads
- Then the user can see a section that describes the store’s goal, mission, values and vision.

### **Tasks**

- [x]  Create and add to the homepage text about the store, its goals, values, mission and vision.
- [x] Test the readability and accessibility of the information.
- [x] Check the responsiveness and visual appeal across different devices to ensure a uniform experience, and adjust layouts and font sizes as needed.

**Comment by KatePaulauskas** [comment]
Site visitors can now read about the store's goal, mission, vision and values on the home page.
