### ISSUE TITLE
USER STORY: Social Media Engagement

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#7]
As a **user** I can see **links to social media profiles in the footer of the site** so that **I can follow the brand and stay connected via social media platforms**.

### **Acceptance Criteria**

- Given a user accesses the homepage or any page of the site
- When the page loads
- Then the user can see links to the store’s social media profiles in the footer

### **Tasks**

- [x] Add social media profile links to the footer.
- [x] Ensure the links are functional.
- [x] Test the visibility and functionality of social media links
- [x] Check the responsiveness and visual appeal across different devices to ensure a uniform experience, and adjust layouts and font sizes as needed.

**Comment by KatePaulauskas** [comment]
Clickable social media links were added to the site footer.
