### ISSUE TITLE
USER STORY: Footer Menu and Contact Information

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#8]
As a **user** I can **easily access contact details and important links in the footer of the site** so that **I can get in touch with the store if needed and quickly navigate to key sections like Home, Shop, Terms & Conditions, Return Policy, Privacy Policy, and Get in Touch**.

### **Acceptance Criteria**

- Given a user accesses the homepage or any other page
- When the page loads
- Then the user can easily find the store’s contact details in the footer
- And the user can access important links such as Home, Shop, Get in Touch, Terms & Conditions, Return Policy, and Privacy Policy from the footer menu

### **Tasks**

- [x] Add contact details to the site footer.
- [x] Add a footer menu with links to important pages or sections, such as Home, Shop, Get in Touch, Terms & Conditions, Return Policy, and Privacy Policy.
- [x] Ensure the contact information is accurate and up-to-date.
- [x] Test the visibility and functionality of the contact details.
- [x] Check the responsiveness and visual appeal across different devices to ensure a uniform experience, and adjust layouts and font sizes as needed.

**Comment by KatePaulauskas** [comment]
The responsive footer with contact details was created successfully.

**Comment by KatePaulauskas** [comment]
A responsive footer menu with important pages such as Home, Shop, Get in Touch, Terms & Conditions, Return Policy, and Privacy Policy was created.

**Comment by KatePaulauskas** [comment]
Policies content was added successfully.
