### ISSUE TITLE
USER STORY: Customer Trust

### ISSUE THREAD

**Issue by KatePaulauskas** [KatePaulauskas/watch-store#9]
As a **user** I can **view customer reviews on the home page** so that **I learn about the quality of the products and level of service from other customers**.

### **Acceptance Criteria**

- Given a user accesses the homepage
- When the homepage loads
- Then the user can see customer reviews and gauge the quality the store product and the level of service.

### **Tasks**

- [ ] Collect customer reviews.
- [ ] Design a section to display customer reviews on the homepage.
- [ ] Test the readability and accessibility of the reviews section.
- [ ] Check the responsiveness and visual appeal across different devices to ensure a uniform experience, adjust layouts and font sizes as needed.

**Comment by KatePaulauskas** [comment]
The issue moved to the backlog.
